name: Publish And Deploy
on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 设置 Secrets
    - name: Set Secret
      run: mkdir /home/runner/.ssh
    - run: echo "${{ secrets.KEY }}" /home/runner/.ssh/id_rsa
    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: "/home/runner/.ssh/id_rsa"
        port: ${{ secrets.PORT }}
        script: |
          cd /home/aynimor
          rm -rf enterprize
          git clone git@github.com:aynimor/enterprize.git
          cd enterprize
          mkdocs build
